#!/bin/bash

cp .vimrc ~

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir ~/.vim/colors

cp nord.vim ~/.vim/colors/nord.vim

vim +'PlugInstall --sync' +qa
